Table notes {
  id uuid [pk, unique, default: `gen_random_uuid()`]
  user_id uuid [not null]
  body TEXT [not null]
  created_at TIMESTAMP [default: `now()`]
  is_important BOOLEAN [default: FALSE]
}

Table goals {
  id uuid [pk, unique, default: `gen_random_uuid()`]
  user_id uuid [not null]
  body VARCHAR(60) [not null]
  created_at TIMESTAMP [default: `now()`]
}

Table users_therapists {
  id uuid [pk, unique, not null, default: `gen_random_uuid()`]
  user_id uuid [not null]
  name VARCHAR(50) [not null]
  email VARCHAR(50)
  phone VARCHAR(50)
  free_from DATE
  therapy_types "VARCHAR(50)[]"
  note TEXT
  street VARCHAR(255)
  street_number VARCHAR(8)
  city VARCHAR(50)
  postal_code VARCHAR(10)

  created_at TIMESTAMP [default: `now()`]

  Indexes {
    (id, user_id) [unique]
  }
}

Table users_call_times {
  therapist_id uuid [not null]
  from VARCHAR(5) [not null]
  to VARCHAR(5) [not null]
  weekday VARCHAR(2) [not null]
  reminder BOOLEAN [default: FALSE]

  Indexes {
    therapist_id
  }
}

Table shared_therapists {
  id uuid [pk, unique, not null, default: `gen_random_uuid()`]
  name VARCHAR(50) [not null]
  email VARCHAR(50)
  phone VARCHAR(50)
  therapy_types "VARCHAR(50)[]"
  street VARCHAR(255)
  street_number VARCHAR(8)
  city VARCHAR(50)
  postal_code VARCHAR(10)
}

Table shared_call_times {
  therapist_id uuid [not null]
  from VARCHAR(5) [not null]
  to VARCHAR(5) [not null]
  weekday VARCHAR(2) [not null]

  Indexes {
    therapist_id
  }
}

Table app_settings {
  user_id uuid [pk, not null]
  call_precaution_time SMALLINT [default: 15, not null]
  appointment_precaution_time SMALLINT [default: 60, not null]
  share_therapist_data BOOLEAN [default: TRUE, not null]
  remind_next_appointment BOOLEAN [default: TRUE, not null]
}

Table sessions {
  user_id uuid [not null]
  id TEXT [unique, not null]
  ip CIDR [not null]
  created_by_full_user BOOLEAN [default: false]
  created_at TIMESTAMP [default: `now()`]
  Indexes {
    (user_id, ip) [unique]
  }
}


Table users {
  id uuid [pk, unique, not null, default: `gen_random_uuid()`]
  name VARCHAR(30)
  secret uuid [unique, default: `gen_random_uuid()`]
  password TEXT
  email VARCHAR(50) [unique]
  is_full_user BOOLEAN [default: FALSE]
  created_at TIMESTAMP [default: `now()`]
}


Table appointments {
  id uuid [pk, unique, default: `gen_random_uuid()`]
  user_id uuid [not null]
  therapist_id uuid
  is_repeating boolean
  weekday VARCHAR(2)
  date DATE
  from VARCHAR(5)
  to VARCHAR(5)
}


Ref: users.id - app_settings.user_id [delete: cascade]
Ref: users.id < notes.user_id [delete: cascade]
Ref: users.id < goals.user_id [delete: cascade]
Ref: users.id < appointments.user_id [delete: cascade]
Ref: users.id < users_therapists.user_id [delete: cascade]
Ref: users.id < sessions.user_id [delete: cascade]

Ref: users_therapists.id < appointments.therapist_id [delete: cascade]
Ref: users_therapists.id <  users_call_times.therapist_id [delete: cascade]

Ref: shared_therapists.id < shared_call_times.therapist_id [delete: cascade]