services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: buddy
      TZ: 'Europe/Berlin'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d