@base = http://localhost:5200
@secret = NDNmNjkyNzktYzFiZi00ZWY5LWJkMGQtZjFjYTA2NDFjNmQ1

### 

POST {{base}}/therapists/find
secret: {{secret}}
content-type: application/json

{
    "therapyTypes": ["Verhaltenstherapie"]
}

###

GET {{base}}/therapists
sessionID: 9dfc6e5d-8abb-4bc8-9b68-fbf480219672



