@base = http://localhost:5200
@secret = NDNmNjkyNzktYzFiZi00ZWY5LWJkMGQtZjFjYTA2NDFjNmQ1

### 

POST {{base}}/therapists/search
secret: {{secret}}
content-type: application/json

{
    # "therapyTypes": ["Verhaltenstherapie"]
}

###

GET {{base}}/therapists
secret: {{secret}}
content-type: application/json



